#!/bin/sh

printf "Password: "
stty -echo
read -r PASS
stty echo
echo

DIGEST=$(printf "%s" "$PASS"|sha1sum|tr '[:lower:]' '[:upper:]')
START=$(echo "$DIGEST"|cut -b1-5)
END=$(echo "$DIGEST"|cut -b6-40)

HASHES=$(curl -s "https://api.pwnedpasswords.com/range/$START")

NUM=$(echo "$HASHES"|awk -F: "/$END/ "'{gsub(/\r/,"");print $2}')

if [ -z "$NUM" ];then
	echo "Good"
else
	echo "$NUM times seen :-("
	exit 1
fi

